Header
NickTsalyn/Food-delivery-service pull request #1
Opened 2023-06-19 21:21 UTC by Rif77777

Створив тіло хедера.

2023-06-19 22:13 UTC, NickTsalyn requested changes

2023-06-19 22:13 UTC, NickTsalyn commented on src/partials/header.html
> +     <a href="#home" class="nav-link link">Home</a>
позабирай клас link з посилань, не потрібно. лишні властивості скинуті. І посилання повинні бути в середині li, а не сусідні.

2023-06-19 22:13 UTC, NickTsalyn commented on src/partials/header.html
> +     <svg class="">
svg має бути в середині button.

2023-06-19 22:13 UTC, NickTsalyn commented on src/partials/header.html
> +  </header>
зроби також розмітку на мобільне меню. адже воно відноситься до твоєї секції

2023-06-20 20:11 UTC, Rif77777 commented on src/partials/header.html
> +     <svg class="">
ok

2023-06-20 20:11 UTC, Rif77777 commented on src/partials/header.html
> +  </header>
добре, буде зроблено

2023-06-20 20:12 UTC, Rif77777 commented on src/partials/header.html
> +     <a href="#home" class="nav-link link">Home</a>
Буде зроблено

2023-06-23 01:38 UTC, NickTsalyn requested changes

2023-06-23 01:38 UTC, NickTsalyn commented on src/partials/header.html
> +     <ul class="mobile-menu-list list">
клас list не потрібний, бо ці скидування є в файлі reset.css

2023-06-25 19:12 UTC, Rif77777 commented
прописав модалки в html, але виеикає якийсь конфлікт
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/NickTsalyn/Food-delivery-service/pull/1/conflicts) or the  to resolve conflicts.
Conflicting files
src/img/icons.svg

2023-06-25 19:16 UTC, closed without merging