Feature/hero css
NickTsalyn/Food-delivery-service pull request #13
Opened 2023-07-01 19:46 UTC by KaterynaSch

2023-07-02 17:15 UTC, NickTsalyn requested changes

2023-07-02 17:15 UTC, NickTsalyn commented on src/css/hero.css
> +  outline: 2px solid red;
а звідки ти взяла цей outline?

2023-07-02 17:15 UTC, NickTsalyn commented on src/css/hero.css
> +.hero-section {
також свайпер не працює

2023-07-02 17:15 UTC, NickTsalyn commented on src/css/hero.css
> +  outline: 2px solid teal;
теж не бачу на макеті outline

2023-07-02 18:21 UTC, KaterynaSch commented on src/css/hero.css
> +  outline: 2px solid red;
додавала собі для координації, забула видалити

2023-07-02 18:22 UTC, KaterynaSch commented on src/css/hero.css
> +.hero-section {
js ще не підключала

2023-07-02 18:23 UTC, KaterynaSch commented on src/css/hero.css
> +  outline: 2px solid teal;
те ж саме що і перший

2023-07-07 23:14 UTC, NickTsalyn requested changes
все гуд. тільки підключи кнопку щоб модалку відкривало, modal.js

2023-07-08 11:01 UTC, KaterynaSch commented on src/partials/modal-order.html
додала до кнопки "order now" посилання на модальне вікно

2023-07-08 20:52 UTC, NickTsalyn approved these changes

2023-07-08 20:52 UTC, merged