Feature/subscribe-HTML
NickTsalyn/Food-delivery-service pull request #5
Opened 2023-06-21 06:04 UTC by Anna211291

HTML розмітка секції

2023-06-23 01:42 UTC, NickTsalyn requested changes

2023-06-23 01:42 UTC, NickTsalyn commented on src/partials/subscribe.html
>          <input
добав тег label. оскільки він покращує доступність сайту)))

2023-06-23 03:28 UTC, Anna211291 commented on src/partials/subscribe.html
>          <input
Добавила. Я його спочатку писала, але подивилася що він мені нічим не поможе, то прибрала)

2023-06-24 17:22 UTC, NickTsalyn approved these changes

2023-06-24 17:22 UTC, merged